title: Bastiana świat programowania
title_en: Bastian's view on programming
author: Michał Piotrowski
#description: Opis

#social links
linkedin_username: michał-piotrowski-0701abb9

show_excerpts: true

timezone: Europe/Warsaw
theme: jekyll-theme-modernist
